### ISSUE TITLE
Error in combined.asm - broken Punch command

### ISSUE THREAD

**Issue by stanleyruppert** [jefftranter/6809#1]
Just ported the combo of Assist09 and Basic to my early 80s Wintek Corp 6809 SBC. Works well. Trace and disassembly functions very helpful!

Found a typo/bug (missing single quote prefix of "1" )in your existing Assist09 code "combined.asm" within the "combined" directory (from GIT). Result is no "1" printed following "S" in a punch text output.

From: combined.asm
original:     BSPSTR FCB 'S,1,EOT ; CR,LF,NULLS,S,1
corrected: BSPSTR FCB 'S,'1,EOT ; CR,LF,NULLS,S,1

In your blog examples you show:

>P 1000 100F
S13100055414C49535449432E22203A2090001014
S9030000FC
(note missing "1" between S and byte count field

Should be: (0x13 bytes following "S1")

>P 1000 100F
S113100055414C49535449432E22203A2090001014
S9030000FC

Kept wondering why my punched output wouldn't then load. Then while debugging tried punching < 0x10 bytes and got a "S0" line, then caught the typo.

Many thanks for putting the assist09/basic combination together!

Some of your assist09 code had the typo, some did not. Y
our s19 examples are correct (have the S1 prefix)

**Comment by jefftranter** [comment]
Thanks for sending that - I will check in the fix.

Regards,
Jeff

**Comment by jefftranter** [comment]
Fix committed.
