### ISSUE TITLE
Assist09 memory function code / documentation mismatch

### ISSUE THREAD

**Issue by stanleyruppert** [jefftranter/6809#2]
In the SBC/combined/README.md you have the following:
snip---
M (emory)	NNNN	- Display memory data at address NNNN
		<cr>	- Terminate memory function
		/	- Display current byte with address
		**.	- Display next byte with address**
		^	- Display previous byte with address
		,	- Skip byte
		SPACE	- Display next byte

Denoting a "." to display next byte with address.
However, the code in combined.asm memory routine looks for a line feed "LF, 0x0A" for this.

`* LINE FEED - NEXT BYTE WITH ADDRESS`
`CMNOTB  CMPA    #LF     ; ? LINE FEED FOR NEXT BYTE`
`        BNE     CMNOTL  ; BRANCH NO`
`        LDA     #CR     ; GIVE CARRIAGE RETURN`
`       SWI             ;TO CONSOLE`
`        FCB     OUTCH   ; HANDLER`
`        STX     <ADDR   ; STORE NEXT ADDRESS`
`        BRA     CMPADP  ; BRANCH TO SHOW`

Couple of suggested options:
1 - update documentation to specify "LF" to display next byte with address, no code change required.
     Should note that many modern keyboards do not have a separate LF key generating 0x0a, only CR key for 0x0d

2 - update code to actually use a "." period - no change to documentation required
`* PERIOD - NEXT BYTE WITH ADDRESS`
`CMNOTB  CMPA    #'.     ; ? PERIOD FOR NEXT BYTE`
`        BNE     CMNOTL  ; BRANCH NO`
`*       LDA     #CR     ; GIVE CARRIAGE RETURN - replace with two NOPs`
`       NOP`
`       NOP`
`       SWI             ;TO CONSOLE`
`*        FCB     OUTCH   ; HANDLER - replace OUTCH with PCRLF`
`        FCB     PCRLF   ;  change to PCRLF HANDLER for SWI lookup - same as in ^ previous byte code below`
`        STX     <ADDR   ; STORE NEXT ADDRESS`
`        BRA     CMPADP  ; BRANCH TO SHOW`

3 - update code to use more convenient keys - I chose to use "[" and "]" for previous byte and next byte respectively as these are on both vintage and modern keyboards and easy to type/access (over going for the ^ in the original code for prev byte

`* RIGHT SQ BRACKET ] - NEXT BYTE WITH ADDRESS`
`CMNOTB  CMPA    #']     ; ? RIGHT SQ BRACKET ] FOR NEXT BYTE`
`        BNE     CMNOTL  ; BRANCH NO`
`*       LDA     #CR     ; GIVE CARRIAGE RETURN - replace with two NOPs`
`       NOP`
`       NOP`
`       SWI             ;TO CONSOLE`
`*        FCB     OUTCH   ; HANDLER - replace OUTCH with PCRLF`
`        FCB     PCRLF   ;  change to PCRLF HANDLER for SWI lookup - same as in ^ previous byte w/address code below`
`        STX     <ADDR   ; STORE NEXT ADDRESS`
`        BRA     CMPADP  ; BRANCH TO SHOW`

`* LEFT SQ BRACKET [  - PREVIOUS BYTE AND ADDRESS`
`CMNOTL  CMPA    #'[             ; ? LEFT SQ BRACKET [ FOR PREVIOUS BYTE`
`        BNE     CMNOTU          ; BRANCH NOT`
`        LEAX    -2,X            ; DOWN TO PREVIOUS BYTE`
`        STX     <ADDR           ; STORE NEW POINTER`
`CMPADS  SWI                     ; FORCE NEW LINE`
`        FCB     PCRLF           ; FUNCTION`
`CMPADP  BSR     PRTADR          ; GO PRINT ITS VALUE`
`        BRA     CMEM2           ; THEN PROMPT FOR INPUT`

**Comment by jefftranter** [comment]
I've updated the README file to match the code (and the original Motorola documentation).
