### ISSUE TITLE
ex4.bas

### ISSUE THREAD

**Issue by Bernard13090** [jefftranter/6809#4]
Thank you for this emazing work.

I use combined ROM and it's running well with ASSIST09 and BASIC 1982.

I try to understand the basic USR function to call ASM piece of program.

The Exemple 4 don't work. 

Have you an idea to solve issue.

Maybe  wrong address => dc 7b                   JMP     GIVABF          ; Return to BASIC

Best Regards

**Comment by jefftranter** [comment]
For the combined ROM, some addresses have changed.
INTCNV should be CB74 and GIVBF should be CC7B.
The files ex4.asm and ex4.bas will need to be changed accordingly.
The listing file here shows the addresses: https://github.com/jefftranter/6809/blob/master/sbc/combined/combined.lst
I will add a note in the code that the addresses will vary depending on which ROM image is being used.

Regards,
Jeff

**Comment by jefftranter** [comment]
Actually I changed the address to be correct for the combined ROM as well.
Change checked in.
